# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doktorrandevular.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -50, 941, 731))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 651, 41))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("20200316220122!Saglikbakanligi_logo (2).png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.randevular = QtWidgets.QTableWidget(self.centralwidget)
        self.randevular.setGeometry(QtCore.QRect(200, 170, 501, 192))
        self.randevular.setRowCount(100)
        self.randevular.setObjectName("randevular")
        self.randevular.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.randevular.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.randevular.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.randevular.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.randevular.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.randevular.setHorizontalHeaderItem(4, item)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 420, 101, 16))
        self.label_4.setObjectName("label_4")
        self.doktoradi = QtWidgets.QLineEdit(self.centralwidget)
        self.doktoradi.setGeometry(QtCore.QRect(600, 420, 131, 20))
        self.doktoradi.setObjectName("doktoradi")
        self.randevuara = QtWidgets.QPushButton(self.centralwidget)
        self.randevuara.setGeometry(QtCore.QRect(750, 420, 91, 23))
        self.randevuara.setObjectName("randevuara")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 897, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">RANDEVULAR</span></p></body></html>"))
        item = self.randevular.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "hasta_id"))
        item = self.randevular.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "klinik_adi"))
        item = self.randevular.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "doktor"))
        item = self.randevular.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "tarih"))
        item = self.randevular.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "saat"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Doktor Adı</span></p></body></html>"))
        self.randevuara.setText(_translate("MainWindow", "Randevu Ara"))
