# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hastapaneli.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -40, 931, 711))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("5c4bd40a58fe131cf068arkaplan2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("20200316220122!Saglikbakanligi_logo (2).png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 651, 41))
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 90, 141, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hastakullanici = QtWidgets.QPushButton(self.layoutWidget)
        self.hastakullanici.setObjectName("hastakullanici")
        self.verticalLayout.addWidget(self.hastakullanici)
        self.recetelerim = QtWidgets.QPushButton(self.layoutWidget)
        self.recetelerim.setObjectName("recetelerim")
        self.verticalLayout.addWidget(self.recetelerim)
        self.randevularim = QtWidgets.QPushButton(self.layoutWidget)
        self.randevularim.setObjectName("randevularim")
        self.verticalLayout.addWidget(self.randevularim)
        self.randevual = QtWidgets.QPushButton(self.layoutWidget)
        self.randevual.setObjectName("randevual")
        self.verticalLayout.addWidget(self.randevual)
        self.randevusil = QtWidgets.QPushButton(self.layoutWidget)
        self.randevusil.setObjectName("randevusil")
        self.verticalLayout.addWidget(self.randevusil)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">HASTA PANELİ</span></p></body></html>"))
        self.hastakullanici.setText(_translate("MainWindow", "Kullanıcı"))
        self.recetelerim.setText(_translate("MainWindow", "Reçetelerim"))
        self.randevularim.setText(_translate("MainWindow", "Randevularım"))
        self.randevual.setText(_translate("MainWindow", "Randevu Al"))
        self.randevusil.setText(_translate("MainWindow", "Randevu Sil"))
