# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ilksayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1027, 685)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1051, 691))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("5c4bd40a58fe131cf068arkaplan2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 30, 821, 81))
        self.label_2.setObjectName("label_2")
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(90, 110, 831, 541))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnyonetici = QtWidgets.QPushButton(self.layoutWidget_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("png-transparent-computer-icons-manager-businessperson-management-administrator-company-human-resource-management-people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnyonetici.setIcon(icon)
        self.btnyonetici.setObjectName("btnyonetici")
        self.verticalLayout.addWidget(self.btnyonetici)
        self.btnhastakabul = QtWidgets.QPushButton(self.layoutWidget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("png-transparent-user-logo-computer-icons-industry-icon-user-experience-room-logo-black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnhastakabul.setIcon(icon1)
        self.btnhastakabul.setObjectName("btnhastakabul")
        self.verticalLayout.addWidget(self.btnhastakabul)
        self.btndoktor = QtWidgets.QPushButton(self.layoutWidget_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("png-transparent-physician-medicine-health-care-clinic-surgery-sick-people-logo-pharmaceutical-drug-silhouette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btndoktor.setIcon(icon2)
        self.btndoktor.setObjectName("btndoktor")
        self.verticalLayout.addWidget(self.btndoktor)
        self.btnlaboratuvar = QtWidgets.QPushButton(self.layoutWidget_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("png-transparent-17th-international-conference-on-pathology-science-student-laboratory-microscope-biomedical-industry-laboratory-experiment-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnlaboratuvar.setIcon(icon3)
        self.btnlaboratuvar.setObjectName("btnlaboratuvar")
        self.verticalLayout.addWidget(self.btnlaboratuvar)
        self.btnhastagiris = QtWidgets.QPushButton(self.layoutWidget_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("png-clipart-organization-company-service-architectural-engineering-management-group-icon-cdr-hand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnhastagiris.setIcon(icon4)
        self.btnhastagiris.setObjectName("btnhastagiris")
        self.verticalLayout.addWidget(self.btnhastagiris)
        self.btnkaydol = QtWidgets.QPushButton(self.layoutWidget_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("png-transparent-computer-icons-register-button-miscellaneous-text-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnkaydol.setIcon(icon5)
        self.btnkaydol.setObjectName("btnkaydol")
        self.verticalLayout.addWidget(self.btnkaydol)
        self.btniletisim = QtWidgets.QPushButton(self.layoutWidget_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btniletisim.setIcon(icon6)
        self.btniletisim.setObjectName("btniletisim")
        self.verticalLayout.addWidget(self.btniletisim)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 111, 101))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("20200316220122!Saglikbakanligi_logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#ffffff;\">Hastane Otomasyon Sistemine Hoşgeldiniz</span></p></body></html>"))
        self.btnyonetici.setText(_translate("Form", "Yönetici Girişi"))
        self.btnhastakabul.setText(_translate("Form", "Hasta Kabul"))
        self.btndoktor.setText(_translate("Form", "Doktor Girişi"))
        self.btnlaboratuvar.setText(_translate("Form", "Laboratuvar"))
        self.btnhastagiris.setText(_translate("Form", "Hasta Girişi"))
        self.btnkaydol.setText(_translate("Form", "Kaydol"))
        self.btniletisim.setText(_translate("Form", "İletişim"))
