# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yoneticipaneli.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 719)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-70, -40, 1091, 791))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("5c4bd40a58fe131cf068arkaplan2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 20, 651, 41))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("20200316220122!Saglikbakanligi_logo (2).png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 151, 571))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnyonetici = QtWidgets.QPushButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("png-transparent-computer-icons-manager-businessperson-management-administrator-company-human-resource-management-people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnyonetici.setIcon(icon)
        self.btnyonetici.setObjectName("btnyonetici")
        self.verticalLayout.addWidget(self.btnyonetici)
        self.yoneticihastalar1 = QtWidgets.QPushButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("png-clipart-organization-company-service-architectural-engineering-management-group-icon-cdr-hand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yoneticihastalar1.setIcon(icon1)
        self.yoneticihastalar1.setObjectName("yoneticihastalar1")
        self.verticalLayout.addWidget(self.yoneticihastalar1)
        self.yoneticidoktorlar = QtWidgets.QPushButton(self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("png-transparent-physician-medicine-health-care-clinic-surgery-sick-people-logo-pharmaceutical-drug-silhouette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yoneticidoktorlar.setIcon(icon2)
        self.yoneticidoktorlar.setObjectName("yoneticidoktorlar")
        self.verticalLayout.addWidget(self.yoneticidoktorlar)
        self.yoneticiklinikler = QtWidgets.QPushButton(self.layoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("hospital-buildings-vector-icon-clinicmedical-260nw-1035393526.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yoneticiklinikler.setIcon(icon3)
        self.yoneticiklinikler.setObjectName("yoneticiklinikler")
        self.verticalLayout.addWidget(self.yoneticiklinikler)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">YÖNETİCİ PANELİ</span></p></body></html>"))
        self.btnyonetici.setText(_translate("MainWindow", "Yönetici"))
        self.yoneticihastalar1.setText(_translate("MainWindow", "Hastalar"))
        self.yoneticidoktorlar.setText(_translate("MainWindow", "Doktorlar"))
        self.yoneticiklinikler.setText(_translate("MainWindow", "Klinikler"))
